### ISSUE TITLE
Problem: combining PREMIS files no longer required

### ISSUE THREAD

**Issue by sallain** [artefactual-sdps/preprocessing-sfa#18]
**Describe the issue**

The client has decided to leave the PREMIS files located in the content directory as-is. The following features will need to be removed:

- [ ] Combine premis.xml files from content directory into a single premis.xml file
- [ ] Delete premis.xml files from content directory

The original description of the work included two move tasks - placing Prozess_Digitalisierung_PREMIS.xml and UpdatedAreldaMetadata.xml in the metadata directory. These moves can remain.

**Comment by fiver-watson** [comment]
Confirmed that PREMIS files are no longer combined in most recent tests
