### ISSUE TITLE
Feature: Add support for Born digital SIPs and update SIP identification rules

### ISSUE THREAD

**Issue by sallain** [artefactual-sdps/preprocessing-sfa#34]
**Is your feature request related to a problem? Please describe.**

SFA has decided to refine the identification of SIP types, in a way that better reflects the business logic that will be applied to the SIP as it is processed. Instead of Vecteur SIP, GEVER SIP, SIARD SIP, etc., there should be three branches for identification:

* **Born digital SIP**: any eCH-0160 compliant SIP
* **Digitized SIP**: what we're currently calling a Vecteur SIP
* **Digitized AIP**: what we're currently calling a Vecteur AIP

**Describe the solution you'd like**

This should be pretty straightforward. At this time, we are not being asked to add any validation logic for Digital born SIPs beyond the XSD checks already in place - we will just presume that any transfer that makes it to DPS conforms to eCH-0160, so we can treat this as the basic type.

Christa has suggested the following differentiators for Digitized SIPs:

* Vecteur SIPs always have the word “Vecteur” in the SIP name
* Vecteur SIPs have PREMIS metadata, one per package (`Prozess_Digitalisierung_PREMIS.xml`) and one for each file in the package (e.g. `00000001.jp2` will have a corresponding `00000001_PREMIS.xml`)

For Digitized AIPs, we can use the same identification check as is currently in place - looking for the `additional` directory.

Just as a note Digitized AIPs will also have the same PREMIS metadata as Digitized SIPs; however, they do not always have the word "Vecteur" in the AIP name.

**Describe alternatives you've considered**

**Additional context**

**Comment by sallain** [comment]
@djjuhasz Samples for all SIP types are available [here](https://drive.google.com/drive/u/0/folders/1H4PUSz8ArqAtwabm_KH9RNK2TAQ-QkIL)

**Comment by fiver-watson** [comment]
Reopening this issue for a low-priority fix - It seems that right now "Vecteur" being in the SIP name is case-sensitive, so a sample like our previous default `little_vecteur_sip` was failing, until I remade it as `little_Vecteur_sip`. 

It would be nice to make this name check case-insensitive!

**Comment by jraddaoui** [comment]
This should be fixed now @fiver-watson.
