### ISSUE TITLE
Feature: use the xmlvalidate activity and SIP XSD files to validate XML metadata

### ISSUE THREAD

**Issue by jraddaoui** [artefactual-sdps/preprocessing-sfa#39]
**Is your feature request related to a problem? Please describe.**

We are still using [a Python script](https://github.com/artefactual-sdps/preprocessing-sfa/blob/main/hack/sampledata/xsd/xsdval.py) and [a fixed local version of the XSD files](https://github.com/artefactual-sdps/preprocessing-sfa/tree/main/hack/sampledata/xsd) to validate the metadata.xml or UpdatedAreldaMetadata.xml files.

**Describe the solution you'd like**

@mcantelon recently created an activity in the temporal-activities respository to perform that validation:

https://github.com/artefactual-sdps/temporal-activities/blob/main/xml/xsd_validate_activity.go

We also need to change the workflow to use the XSD files contained on each SIP instead of the fixed ones copied into the environment.

**Comment by sallain** [comment]
This looks like it's working - packages are failing and succeeding on metadata validations appropriately.
