### ISSUE TITLE
Feature: import file identifiers from metadata.xml into METS

### ISSUE THREAD

**Issue by sallain** [artefactual-sdps/preprocessing-sfa#53]
**Is your feature request related to a problem? Please describe.**

Each file in an SFA SIP has a unique file identifier, which is listed in the package's metadata.xml file as `<datei id="_zodSTSD0nv05CpOp6JoV3X">`. This identifier is widely used in AIS to connect information across many sources. SFA would like this identifier to be present in the METS file so that the METS data can also be connected using the identifier.

**Describe the solution you'd like**

There are a few different options we could implement:

1. We could add a second `<premis:objectIdentifier>` to the premis.xml implementation that is already in place; alternately, I _think_ that the premis.xml relies on `<premis:originalName>` to connect the premis object to the METS metadata, so we could perhaps have JUST the SFA identifier as the `<premis:objectIdentifier>`.
2. We could use Archivematica's [identifiers.json](https://www.archivematica.org/en/docs/archivematica-1.16/user-manual/transfer/transfer/#transfer-pids) feature to bypass doing the above PREMIS work, which has the same result (creates a second `<premis:objectIdentifier>`)

**Describe alternatives you've considered**

These are the two options I could think of!

**Additional context**

**Comment by djjuhasz** [comment]
I'm going to try replacing the `<premis:objectIdentifier>` UUID with the SFA file identifier value.  If we have problems with that solution then I'll add the SFA identifier as an additional `<premis:objectIdentifier>`.

**Comment by djjuhasz** [comment]
Unfortunately Archivematica seems to ignore the premis.xml <objectIdentifierValue> values (#56) and just generates it's own UUIDs to use as <objectIdentifierValue> in the METS file. :(

I've confirmed the manifest file ids are being used in the premis.xml file generated by preprocessing-sfa, e.g:
```
<premis:object xsi:type="premis:file">
    <premis:objectIdentifier>
      <premis:objectIdentifierType>local</premis:objectIdentifierType>
      <premis:objectIdentifierValue>_zodSTSD0nv05CpOp6JoV3X</premis:objectIdentifierValue>
    </premis:objectIdentifier>
    <premis:objectCharacteristics>
      <premis:format>
        <premis:formatDesignation>
          <premis:formatName/>
        </premis:formatDesignation>
      </premis:format>
    </premis:objectCharacteristics>
    <premis:originalName>data/objects/little_digitized_sip/content/d_0000001/00000001.jp2</premis:originalName>
    <premis:linkingEventIdentifier>
      <premis:linkingEventIdentifierType>UUID</premis:linkingEventIdentifierType>
      <premis:linkingEventIdentifierValue>38f00a58-0625-4187-af29-d3e8f2fce2a4</premis:linkingEventIdentifierValue>
    </premis:linkingEventIdentifier>
    <premis:linkingEventIdentifier>
      <premis:linkingEventIdentifierType>UUID</premis:linkingEventIdentifierType>
      <premis:linkingEventIdentifierValue>c7fb4b09-c573-4956-92f6-d534c45e69bf</premis:linkingEventIdentifierValue>
    </premis:linkingEventIdentifier>
    <premis:linkingEventIdentifier>
      <premis:linkingEventIdentifierType>UUID</premis:linkingEventIdentifierType>
      <premis:linkingEventIdentifierValue>410d7eb8-39fa-46c3-9dc1-1bfff637c651</premis:linkingEventIdentifierValue>
    </premis:linkingEventIdentifier>
  </premis:object>
```

But the identifier "_zodSTSD0nv05CpOp6JoV3X" doesn't appear anywhere in the Archivematica METS file. :(

**Comment by djjuhasz** [comment]
I think we're going to have to write an [identifiers.json](https://www.archivematica.org/en/docs/archivematica-1.16/user-manual/transfer/transfer/#transfer-pids) file to preserve the SFA file ids in the Archiveamatica METS file.

**Comment by aseles13** [comment]
I am seeing the datei id from the metadata.xml ![Image](https://github.com/user-attachments/assets/0b02f45d-0756-4f82-8066-3a9973728f6a) appearing in the premis: objectIdentifierValue ![Image](https://github.com/user-attachments/assets/ec683041-0ae8-4dd1-9f34-6c1072d3f513)

@sallain I believe this is the expected behaviour? Just wanted to double check to make sure.

**Comment by sallain** [comment]
@aseles13 LGTM!
