### ISSUE TITLE
Problem: Prozess_Digitalisierung_PREMIS.xml should not append the parent directory name when moved to the metadata folder

### ISSUE THREAD

**Issue by jraddaoui** [artefactual-sdps/preprocessing-sfa#58]
**Describe the bug**

We thought it would be possible to include multiple dossiers in the same digitized SIP and appended the parent directory (dossier) name to avoid file name conflicts in the metadata directory.

**To Reproduce**

Ingest a digitized SIP type that includes a Prozess_Digitalisierung_PREMIS.xml file.

**Expected behavior**

Prozess_Digitalisierung_PREMIS.xml should be moved as it is to the metadata directory.

**Comment by jraddaoui** [comment]
Parent directory name is appended in:

https://github.com/artefactual-sdps/preprocessing-sfa/blob/main/internal/activities/transform_sip.go#L46-L55

It's also checked in:

https://github.com/artefactual-sdps/preprocessing-sfa/blob/main/internal/pips/pips.go#L46-L51
https://github.com/artefactual-sdps/preprocessing-sfa/blob/main/internal/premis/premis.go#L380-L384

**Comment by sallain** [comment]
LGTM!
