### ISSUE TITLE
Feature: use relative paths instead of absolute paths in error messages

### ISSUE THREAD

**Issue by sallain** [artefactual-sdps/preprocessing-sfa#59]
**Is your feature request related to a problem? Please describe.**

When a user reviews an error message for a validation activity that failed, they are shown the absolute path of the problematic file or directory. The absolute path is long and much of it is meaningless to the average user; in talk-aloud testing, we found that they skipped right over it and were unable to identify which file or directory was causing the issue.

![image](https://github.com/user-attachments/assets/342011ac-f413-4e32-93bc-6bd1e4fa7307)

The absolute path is used in error messages in the following activities:

* _Validate SIP structure_
* _Validate SIP file formats_

On a related, but inverse, note, _Verify SIP manifest_ seems to be already using relative paths, though actually it might be TOO short. For the sake of consistency, all paths should start at the top-level SIP directory.

![image](https://github.com/user-attachments/assets/6e43709a-ab84-4212-914b-13d7b1031420)

**Describe the solution you'd like**

Using the relative path of the file, starting at the top-level directory of the SIP, should make the path more comprehensible to users.

**Describe alternatives you've considered**

Can't really think of any - we need to provide enough information that the file/directory is uniquely identifiable, but not too much. Hopefully this is the right balance.

**Additional context**

This is a child issue of #43

**Comment by sallain** [comment]
LGTM!

**Comment by fiver-watson** [comment]
@DanielCosme @sallain I see that feedback was added to this, but i am not sure it was noticed, so I am leaving this comment and moving this card back to in progress, so that the additional absolute paths found during QA above can be addressed at some point.
