### ISSUE TITLE
Problem: there is no preservation task in the UI for "Create premis.xml"

### ISSUE THREAD

**Issue by sallain** [artefactual-sdps/preprocessing-sfa#73]
**Describe the bug**

The premis.xml file is generated during Ingest, but this information isn't displayed in the UI. A similar job, "Create identifier.json", has a UI task:

![image](https://github.com/user-attachments/assets/509eb490-fe44-4019-958f-0d43aa69eed5)

**To Reproduce**

1. Go to package details page
2. Expand Preservation Action section and scroll down to validation tasks
3. No task!

**Expected behavior**

There should be a task for premis.xml generation, called "Create premis.xml". The Note should read `Created a premis.xml and stored in metadata directory`.

**Screenshots**

**Additional context**

**Comment by mcantelon** [comment]
PR for CR: https://github.com/artefactual-sdps/preprocessing-sfa/pull/85

**Comment by mcantelon** [comment]
(PR merged.)

**Comment by fiver-watson** [comment]
I see it! "Created a premis.xml and stored in metadata directory" 🎉
