### ISSUE TITLE
Problem: note for identifier.json task in UI doesn't indicate that file is stored in package

### ISSUE THREAD

**Issue by sallain** [artefactual-sdps/preprocessing-sfa#74]
**Describe the bug**

The task in the UI indicates that the file was created, but not that it was stored.

**To Reproduce**

1. Go to package detail page
2. Click on Preservation Actions and scroll down to the validation events
3. Review identifier.json task

**Expected behavior**

The Note should read `Created an identifier.json and stored in metadata directory`.

**Screenshots**

**Additional context**

**Comment by mcantelon** [comment]
PR for CR: https://github.com/artefactual-sdps/preprocessing-sfa/pull/86

**Comment by mcantelon** [comment]
(PR merged.)

**Comment by fiver-watson** [comment]
LGTM! 🎉 🥇
