### ISSUE TITLE
Problem: Born Digital AIPs are not being identified correctly

### ISSUE THREAD

**Issue by sallain** [artefactual-sdps/preprocessing-sfa#79]
**Describe the bug**

The Identify SIP structure activity is currently identifying three types of transfers: `BornDigital`, `DigitizedSIP`, and `DigitizedAIP`. However, there should be four - the two Digitized types as well as `BornDigitalSIP` and `BornDigitalAIP`. I think in a previous issue I failed to properly differentiate between the two different types of AIP - apologies. Right now, the activity is identifying all AIPs as DigitizedAIP.

**To Reproduce**

1. Upload a born digital AIP (e.g. 1-Test-AIP-Files.zip or 2-Test-AIP-GEVER.zip)
2. Review the output for the task `Identify SIP structure` - the result will be `SIP structure identified: DigitizedAIP`

**Expected behavior**

A born digital SIP should be identified as `BornDigitalSIP` (this is just a name change to the existing `BornDigital`). A born digital AIP should be identified as `BornDigitalAIP`

The criteria for all four types is as follows:

* `BornDigitalSIP` - this is the base type; assume this is the type unless other conditions are met
* `DigitizedSIP` - contains _Prozess_Digitalisierung_PREMIS.xml_ file, DOES NOT contain _additional_ directory
* `BornDigitalAIP` - contains _additional_ directory, DOES NOT contain _Prozess_Digitalisierung_PREMIS.xml_ file
* `DigitizedAIP` - contains _additional_ directory AND contains _Prozess_Digitalisierung_PREMIS.xml_ file

**Screenshots**

**Additional context**

**Comment by mcantelon** [comment]
@sallain There's a comment in our code that says "there can only be one dossier in a digitized SIP". Is that true for AIPs as well?

**Comment by mcantelon** [comment]
PR merged.
