### ISSUE TITLE
Problem: Born Digital AIPs fail with a "verify manifest" error

### ISSUE THREAD

**Issue by djjuhasz** [artefactual-sdps/preprocessing-sfa#90]
**Describe the bug**

When a born digital AIP is sent to preprocessing (e.g. [1-Test-AIP-Files.zip](https://github.com/user-attachments/files/17927259/1-Test-AIP-Files.zip)) the validate structure activity fails returns the following validation errors:
```json
"Failures": [
      "XSD folder is missing",
      "metadata.xml is missing",
      "Unexpected directory: \"Test-AIP-Files/additional\""
]
```

And the verify manifest activity returns the following error:
> "verify manifest: parse manifest: open: open /home/preprocessing/shared/Test-AIP-Files/header/metadata.xml: no such file or directory"

**To Reproduce**

1. Upload the attached AIP to Enduro, with the preprocessing-sfa child workflow active
2. The above errors occur and processing fails

**Expected behavior**

The SIP should validate and be sent to preservation successfully.

**Screenshots**

![image](https://github.com/user-attachments/assets/9e56b951-b664-4b30-9e4c-8d494c8ad70f)

**Additional context**

The SIP structure set in https://github.com/artefactual-sdps/preprocessing-sfa/blob/main/internal/sip/sip.go#L95 is using the same Manifest and Metadata paths as the `bornDigitalSIP()`, but I believe it should use the `digitizedAIP()` paths instead.

**Comment by sallain** [comment]
This seems to be fixed. The SIP is identified as BornDigitalAIP and the SIP structure is valid.

Note that I had to update the test package with a logical metadata file to comply with work done in #98.
