### ISSUE TITLE
Feature: if a package is a bag, do not double-bag at the end of the child workflow

### ISSUE THREAD

**Issue by sallain** [artefactual-sdps/preprocessing-sfa#94]
**Is your feature request related to a problem? Please describe.**

Currently, all packages are bagged at the end of the child workflow, before being sent to preservation. So far this hasn't been an issue as all of our testing material was unbagged. However, we have recommended to SFA that they bag all of the migration packages prior to ingest. In the current workflow, the package will be double-bagged. This seems inadvisable.

**Describe the solution you'd like**

Check if the package is a bag, and if so then avoid double-bagging. I can think of two options:

1. [Update bag manifests](https://github.com/LibraryOfCongress/bagit-python/tree/master?tab=readme-ov-file#update-bag-manifests) -- this might be sufficient? I haven't tested it.

2. If option 1 is not sufficient, unbag the package at some point in the process (after #93) and then re-bag it at the end.

**Describe alternatives you've considered**

**Additional context**

**Comment by djjuhasz** [comment]
@sallain I think unbagging the SIP after we've validated the bag will be easier and faster than trying to update the existing bag manifest.

**Comment by fiver-watson** [comment]
blocked from testing currently by #93

**Comment by sallain** [comment]
This seems to be working as expected! I transferred a bag, which was validated and then unbagged. At the end of the whole workflow, I get an AIP that is bagged properly (not double-bagged) with all of the contents in the right place 🎉
